BASE_URL = "https://reddit34.p.rapidapi.com"
RAPID_API_HOST = "reddit34.p.rapidapi.com" 
POPULAR_POST_ENDPOINT = "/getTopPopularPosts"
POST_DETAILS_ENDPOINT = "/getPostDetails"
SUBREDDIT_POSTS_ENDPOINT = "/getPostsBySubreddit"